# Model settings
val_every: 1
model_checkpoint_interval: 1
seed: 0
model:
  name: LaneATT
  parameters:
    # backbone: resnet34
    S: &S 72
    topk_anchors: 1000
    anchors_freq_path: 'data/culane_anchors_freq.pt'
    img_h: &img_h 1020
    img_w: &img_w 1920
batch_size: 8
epochs: 100
loss_parameters: {}
train_parameters:
  conf_threshold:
  nms_thres: 15.
  nms_topk: 3000
test_parameters:
  conf_threshold: 0.2
  nms_thres: 40.
  nms_topk: &max_lanes 14
optimizer:
  name: Adam
  parameters:
    lr: 0.0003
lr_scheduler:
  name: CosineAnnealingLR
  parameters:
    T_max: 166650 # 15 * 11110 iterations

# Dataset settings
datasets:
  train:
    type: LaneDataset
    parameters:
      S: *S
      dataset: once
      split: train
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 1.0
      augmentations:
        - name: Affine
          parameters:
            translate_px:
             x: !!python/tuple [-25, 25]
             y: !!python/tuple [-10, 10]
            rotate: !!python/tuple [-6, 6]
            scale: !!python/tuple [0.85, 1.15]
        - name: HorizontalFlip
          parameters:
            p: 0.5

      root: "/data1/pbw/ONCE_3DLanes/"

  test:
    type: LaneDataset
    parameters:
      S: *S
      dataset: once
      split: test
      img_size: [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 0
      augmentations:
      root: "/data1/pbw/ONCE_3DLanes/"

  val:
    type: LaneDataset
    parameters:
      S: *S
      dataset: once
      split: val
      img_size:  [*img_h, *img_w]
      max_lanes: *max_lanes
      normalize: false
      aug_chance: 0
      augmentations:
      root: "/data1/pbw/ONCE_3DLanes/"
